
import React, { useState } from 'react';
import { Send, Mail, User, MessageSquare, Briefcase, CheckCircle2, Loader2, AlertCircle, Database } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

/**
 * DATABASE CONFIGURATION
 * 1. Create a project at https://supabase.com
 * 2. Replace the placeholders below with your actual Project URL and Anon Key.
 * 3. In your Supabase SQL Editor, run:
 *    CREATE TABLE inquiries (
 *      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *      created_at TIMESTAMPTZ DEFAULT NOW(),
 *      name TEXT,
 *      email TEXT,
 *      service TEXT,
 *      message TEXT
 *    );
 */
const supabaseUrl = 'https://wfwiavhghixnwdojkbts.supabase.co'; // REPLACE WITH YOUR URL
const supabaseKey = 'sb_publishable_qgCGM8SMmQyfTg93B4NF1A_kSwkcdg9'; // REPLACE WITH YOUR KEY

// Safe initialization to prevent app crash if URL is invalid/placeholder
const isSupabaseConfigured = supabaseUrl.includes('supabase.co') && !supabaseUrl.includes('your-project-id');
const supabase = isSupabaseConfigured ? createClient(supabaseUrl, supabaseKey) : null;

export const ContactForm: React.FC = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    service: '',
    message: ''
  });

  const [status, setStatus] = useState<'idle' | 'submitting' | 'success' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState('');

  const services = [
    "Cybersecurity Consulting",
    "ISO 27001 Training/Audit",
    "CEH Training Program",
    "ISO 42001 AI Management",
    "CYBER SECURITY Essentials",
    "Compliance & Policy Management",
    "ISO 27001 / 27701 Audit",
    "SOC Audit",
    "IRDAI Audit",
    "SEBI (System & Cyber Audit)",
    "INTERNAL AUDITS",
    "Regulatory and Compliance Audits",
    "VAPT & Red Teaming",
    "Surveillance Audits",
    "Third-Party & Vendor Security Audits",
    "PCI DSS Audits",
    "DPDP Compliance Audit",
    "Web Accessibility Audit (WCAG)",
    "Secure Source Code Review"
  ];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Basic frontend validation
    if (!formData.name || !formData.email || !formData.service) {
      setStatus('error');
      setErrorMessage('Please fill in all required fields.');
      return;
    }

    // Check if Supabase is properly configured
    if (!supabase) {
      setStatus('error');
      setErrorMessage('Database connection not configured. Please add your Supabase credentials in ContactForm.tsx.');
      console.warn('Supabase is not configured. Form submission ignored.');
      return;
    }

    setStatus('submitting');

    try {
      // Direct PostgreSQL insert via Supabase
      const { error } = await supabase
        .from('inquiries')
        .insert([
          { 
            name: formData.name, 
            email: formData.email, 
            service: formData.service, 
            message: formData.message 
          }
        ]);

      if (error) throw error;

      setStatus('success');
      setFormData({ name: '', email: '', service: '', message: '' });
    } catch (err: any) {
      console.error('Database Error:', err);
      setStatus('error');
      setErrorMessage(err.message || 'Something went wrong while saving to the database.');
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormData(prev => ({
      ...prev,
      [e.target.name]: e.target.value
    }));
    if (status === 'error') setStatus('idle');
  };

  if (status === 'success') {
    return (
      <div className="max-w-4xl mx-auto px-4 text-center py-20 animate-in fade-in zoom-in duration-500">
        <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-emerald-500/20 border border-emerald-500/50 mb-6 shadow-[0_0_30px_rgba(16,185,129,0.2)]">
          <CheckCircle2 className="w-10 h-10 text-emerald-500" />
        </div>
        <h2 className="text-4xl font-bold text-white mb-4">Inquiry Recorded!</h2>
        <p className="text-zinc-400 mb-8 max-w-md mx-auto leading-relaxed">
          Your details have been successfully saved to our <span className="text-emerald-400 font-semibold">PostgreSQL</span> secure vault. A specialist will review your request shortly.
        </p>
        <button 
          onClick={() => setStatus('idle')}
          className="px-8 py-3 rounded-xl bg-zinc-900 border border-zinc-800 text-white font-bold hover:bg-zinc-800 transition-all shadow-xl"
        >
          Send Another Message
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4">
      <div className="text-center mb-16">
        <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">Let's Secure Your <span className="text-amber-400 gold-text-glow">Future</span></h2>
        <p className="text-zinc-400">Your inquiry will be directly stored in our secure compliance database.</p>
      </div>

      <div className="relative group p-1 rounded-3xl bg-gradient-to-br from-blue-500/20 via-amber-400/20 to-purple-500/20">
        <div className="bg-zinc-950/90 backdrop-blur-xl rounded-[calc(1.5rem-2px)] p-8 md:p-12">
          <form className="grid grid-cols-1 md:grid-cols-2 gap-8" onSubmit={handleSubmit}>
            <div className="space-y-6">
              <div className="space-y-2">
                <label className="text-sm font-semibold text-zinc-400 flex items-center gap-2">
                  <User className="w-4 h-4 text-amber-400" /> Full Name *
                </label>
                <input 
                  type="text" 
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  placeholder="John Doe"
                  required
                  className="w-full bg-zinc-900/50 border border-zinc-800 focus:border-amber-400/50 focus:ring-1 focus:ring-amber-400/50 rounded-xl px-4 py-3 text-white transition-all outline-none"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-zinc-400 flex items-center gap-2">
                  <Mail className="w-4 h-4 text-amber-400" /> Email Address *
                </label>
                <input 
                  type="email" 
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="john@company.com"
                  required
                  className="w-full bg-zinc-900/50 border border-zinc-800 focus:border-amber-400/50 focus:ring-1 focus:ring-amber-400/50 rounded-xl px-4 py-3 text-white transition-all outline-none"
                />
              </div>
            </div>

            <div className="space-y-6">
              <div className="space-y-2">
                <label className="text-sm font-semibold text-zinc-400 flex items-center gap-2">
                  <Briefcase className="w-4 h-4 text-amber-400" /> Select Service *
                </label>
                <div className="relative">
                  <select 
                    name="service"
                    value={formData.service}
                    onChange={handleChange}
                    required
                    className="w-full bg-zinc-900/50 border border-zinc-800 focus:border-amber-400/50 focus:ring-1 focus:ring-amber-400/50 rounded-xl px-4 py-3 text-white transition-all outline-none appearance-none cursor-pointer"
                  >
                    <option value="" disabled>Choose a service...</option>
                    {services.map((service, idx) => (
                      <option key={idx} value={service} className="bg-zinc-950 text-white">{service}</option>
                    ))}
                  </select>
                  <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none text-amber-400">
                    <svg className="w-4 h-4 fill-current" viewBox="0 0 20 20">
                      <path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" />
                    </svg>
                  </div>
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-zinc-400 flex items-center gap-2">
                  <MessageSquare className="w-4 h-4 text-amber-400" /> Your Message
                </label>
                <textarea 
                  name="message"
                  value={formData.message}
                  onChange={handleChange}
                  rows={2}
                  placeholder="Any additional details..."
                  className="w-full bg-zinc-900/50 border border-zinc-800 focus:border-amber-400/50 focus:ring-1 focus:ring-amber-400/50 rounded-xl px-4 py-3 text-white transition-all outline-none resize-none"
                />
              </div>
            </div>

            {status === 'error' && (
              <div className="md:col-span-2 flex items-center gap-2 text-red-400 text-sm bg-red-400/10 p-3 rounded-lg border border-red-400/20 animate-in fade-in slide-in-from-top-2">
                <AlertCircle className="w-4 h-4" /> {errorMessage}
              </div>
            )}

            <div className="md:col-span-2">
              <button 
                type="submit"
                disabled={status === 'submitting'}
                className="w-full py-4 rounded-xl bg-amber-400 text-zinc-950 font-bold flex items-center justify-center gap-2 hover:bg-amber-300 transition-all gold-glow group disabled:opacity-70 disabled:cursor-not-allowed"
              >
                {status === 'submitting' ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Saving to Database...
                  </>
                ) : (
                  <>
                    Send Inquiry <Send className="w-4 h-4 group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform" />
                  </>
                )}
              </button>
            </div>
          </form>
          
          <div className="mt-12 flex flex-wrap justify-center gap-8 text-zinc-500 text-sm">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-emerald-500" />
              Secure PostgreSQL Storage
            </div>
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-blue-400" />
              AES-256 Encrypted
            </div>
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-purple-400" />
              GDPR Compliant
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
